"""API routes."""
from flask import jsonify, request, current_app
from app.api import api_bp


@api_bp.route('/', methods=['GET'])
def api_index():
    """API root endpoint."""
    return jsonify({
        'message': 'API endpoint',
        'version': '1.0.0',
        'endpoints': {
            'examples': '/api/examples',
            'echo': '/api/echo'
        }
    }), 200


@api_bp.route('/examples', methods=['GET'])
def get_examples():
    """Get example data."""
    examples = [
        {'id': 1, 'name': 'Example 1', 'description': 'First example'},
        {'id': 2, 'name': 'Example 2', 'description': 'Second example'},
        {'id': 3, 'name': 'Example 3', 'description': 'Third example'}
    ]
    return jsonify({
        'success': True,
        'data': examples,
        'count': len(examples)
    }), 200


@api_bp.route('/examples/<int:example_id>', methods=['GET'])
def get_example(example_id):
    """Get a specific example by ID."""
    # Mock data - replace with actual database query
    example = {
        'id': example_id,
        'name': f'Example {example_id}',
        'description': f'Description for example {example_id}'
    }
    return jsonify({
        'success': True,
        'data': example
    }), 200


@api_bp.route('/examples', methods=['POST'])
def create_example():
    """Create a new example."""
    data = request.get_json()
    
    if not data:
        return jsonify({
            'success': False,
            'error': 'No data provided'
        }), 400
    
    # Validate required fields
    required_fields = ['name', 'description']
    missing_fields = [field for field in required_fields if field not in data]
    
    if missing_fields:
        return jsonify({
            'success': False,
            'error': f'Missing required fields: {", ".join(missing_fields)}'
        }), 400
    
    # Mock response - replace with actual database insert
    new_example = {
        'id': 999,  # Would be generated by database
        'name': data['name'],
        'description': data['description']
    }
    
    current_app.logger.info(f'Created new example: {new_example}')
    
    return jsonify({
        'success': True,
        'message': 'Example created successfully',
        'data': new_example
    }), 201


@api_bp.route('/examples/<int:example_id>', methods=['PUT', 'PATCH'])
def update_example(example_id):
    """Update an existing example."""
    data = request.get_json()
    
    if not data:
        return jsonify({
            'success': False,
            'error': 'No data provided'
        }), 400
    
    # Mock response - replace with actual database update
    updated_example = {
        'id': example_id,
        'name': data.get('name', f'Example {example_id}'),
        'description': data.get('description', 'Updated description')
    }
    
    current_app.logger.info(f'Updated example {example_id}')
    
    return jsonify({
        'success': True,
        'message': 'Example updated successfully',
        'data': updated_example
    }), 200


@api_bp.route('/examples/<int:example_id>', methods=['DELETE'])
def delete_example(example_id):
    """Delete an example."""
    # Mock response - replace with actual database delete
    current_app.logger.info(f'Deleted example {example_id}')
    
    return jsonify({
        'success': True,
        'message': f'Example {example_id} deleted successfully'
    }), 200


@api_bp.route('/echo', methods=['POST'])
def echo():
    """Echo back the received JSON data."""
    data = request.get_json()
    
    return jsonify({
        'success': True,
        'echo': data,
        'method': request.method,
        'content_type': request.content_type
    }), 200
